
node: controller.cpp
	g++ -o node controller.cpp -lpthread -Wall

nodec1: controller.cpp
	g++ -o nodec1 controller.cpp -lpthread -Wall

nodec2: controller.cpp
	g++ -o nodec2 controller.cpp -lpthread -Wall

nodec3: controller.cpp
	g++ -o nodec3 controller.cpp -lpthread -Wall

nodec4: controller.cpp
	g++ -o nodec4 controller.cpp -lpthread -Wall

clean:
	rm -f node nodec1 nodec2 nodec3 nodec4

